name: CI Pipeline for Static HTML App

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: us-east-2                  # set this to your preferred AWS region, e.g. us-west-1
  
permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v4
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload Static Files as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-website
        path: |
          index.html
          style.css
          script.js

